Updating profile_page_metrics
Added a try/except statement to previously line 120 (value=value['count']. This creates an error when there is no ['ProfilePage'] data. The try/except also added a statement of error that no profile data was found.

Then gave the following issue:
[DISCOVER BOT] Account exists.
Traceback (most recent call last):
  File "discover_script.py", line 93, in <module>
    bot.start_bot()
  File "discover_script.py", line 34, in start_bot
    self.discover_new_accounts_through_hashtags(hashtags, category)
  File "discover_script.py", line 75, in discover_new_accounts_through_hashtags
    accounts = self.scraper.discover_accounts_from_hashtag(hashtag)
  File "G:\OneDrive\Academia\Acies-Digital\Web Apps\Testing\Instagram\Jakobowsky\InfluencerDB-YouTube\scripts\scrap.py", line 170, in discover_accounts_from_hashtag
    posts_ids = self.discover_posts(hashtag)
  File "G:\OneDrive\Academia\Acies-Digital\Web Apps\Testing\Instagram\Jakobowsky\InfluencerDB-YouTube\scripts\scrap.py", line 152, in discover_posts
    raise e
  File "G:\OneDrive\Academia\Acies-Digital\Web Apps\Testing\Instagram\Jakobowsky\InfluencerDB-YouTube\scripts\scrap.py", line 149, in discover_posts
    metrics = json_data['entry_data']['TagPage'][0]['graphql']['hashtag']['edge_hashtag_to_top_posts'][
KeyError: 'TagPage'

Then removed raise exception and added a pass to the code due to empty or erroneous accounts info.